export const types = {
  REQUEST_INIT: "REQUEST_INIT",
  SUCCESS_INIT: "SUCCESS_INIT",
  ADD_TO_CART: "ADD_TO_CART",
  GET_CART: "GET_CART",
  SUCCESS_CART: "SUCCESS_CART",
  REMOVE_CART: "REMOVE_CART",
  DEREMENT_QUANTITY: "DEREMENT_QUANTITY",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  PROCEED_CHECKOUT: "PROCEED_CHECKOUT",
  SUCCESS_CHECKOUT: "SUCCESS_CHECKOUT",
  AUTH_STATUS: "AUTH_STATUS",
  DO_LOGIN: "DO_LOGIN",
  DO_LOGOUT: "DO_LOGOUT",
  SUCCESS_WISHLIST: "SUCCESS_WISHLIST",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",

  RECEIVE_CATEGORY_API_DATA: "RECEIVE_CATEGORY_API_DATA",
  REQUEST_CATEGORY_API_DATA: "REQUEST_CATEGORY_API_DATA",

  RECEIVE_PRODUCT_API_DATA: "RECEIVE_PRODUCT_API_DATA",
  REQUEST_PRODUCT_API_DATA: "REQUEST_PRODUCT_API_DATA",

  RECEIVE_CAROUSEL_API_DATA: "RECEIVE_CAROUSEL_API_DATA",
  REQUEST_CAROUSEL_API_DATA: "REQUEST_CAROUSEL_API_DATA",

  REQUEST_REGISTER_USER: "REQUEST_REGISTER_USER",
  RECEIVE_REGISTER_USER: "RECEIVE_REGISTER_USER",

  RECEIVE_LOGIN_USER: "RECEIVE_LOGIN_USER",

  REQUEST_UPDATE_PROFILE: "REQUEST_UPDATE_PROFILE",
  REQUEST_COUPON_DATA: "REQUEST_COUPON_DATA",
  RECEIVE_COUPON_DATA: "RECEIVE_COUPON_DATA",

  REMOVE_COUPON_DATA: "REMOVE_COUPON_DATA",

  REQUEST_ORDER_PLACE: "REQUEST_ORDER_PLACE",
  RECEIVE_ORDER_PLACE: "RECEIVE_ORDER_PLACE",

  REQUEST_CONTINUE_AS_A_GUEST: "REQUEST_CONTINUE_AS_A_GUEST",

  RECEIVE_GET_ORDERS: "RECEIVE_GET_ORDERS",
  LOADING_STATE: "LOADING_STATE",

  ORDER_SUCCESS_MODAL: "ORDER_SUCCESS_MODAL",
  REMOVE_ORDER_LOADING_STATE: "REMOVE_ORDER_LOADING_STATE",

};
